### ISSUE TITLE
Better way to add applications in the Ignore List

### ISSUE THREAD

**Issue by ksdrummer** [jqno/gnome-one-window-wonderland#2]
Hello,

first of all, thank you for this extension which is really useful.

The only problem I have with it is that I can't find the right name to put in the Ignore List. Especially for the ones having multiple words in their names. My laptop is in french, so for VLC I tried :
- vlc
- VLC
- "Lecteur\ multimédia\ VLC" (this is the one appearing in the gnome overview)
- "VLC\ media\ player"
None of them seems to work.

For the application audio recorder I was able to make it work using "Enregistreur\ Audio". I assumed that it is case sensitive and that I have to replace spaces by "\ ".

I don't know the best solution to this problem, but for sure having the ability to pick from an app list would be awesome.

Thank you for reading and for this great extension !

**Comment by jqno** [comment]
I'm glad you like it!

You're right that you have to take the name from the GNOME overview, and that it's case sensitive, but you don't have to put in the backslashes. Also, don't put spaces around the commas. For me (an English language install) `VLC media player` and `Extension Manager` both work, but `VLC\ media\ player` and `Extension\ Manager` don't. I have to admit I haven't tested with accented letters, so I hope that works fine. In your case, I would add `Lecteur multimédia VLC,Enregistreur Audio`. This applies to both the Ignore list and the Force list.

Having a list to pick from is a very good idea, I'll try to add that for the next release. I'll also make the textbox a bit more forgiving (make it case insensitive, allow for spaces around commas). But I have to admit that I just started out messing with GNOME extensions, so I still need time to figure things out :sweat_smile:

**Comment by jqno** [comment]
Just a heads-up: I just published a new version, which includes a button to pick the application from a list. Also, the check is now case-insensitive. I hope this helps you!

**Comment by ksdrummer** [comment]
Thank you so much for your reactivity !

I assumed that the backslashes are needed because "Pianoteq\ 8" works but not "Pianoteq 8".... weird

Anyway picking from a list will make it so much easier ! Thank you !

**Comment by jqno** [comment]
Please let me know if it works for you, including VLC and this Pianoteq.

**Comment by ksdrummer** [comment]
Yes it does, thank you so much for the reactivity !

**Comment by jqno** [comment]
Awesome!
