### ISSUE TITLE
Support gnome 45

### ISSUE THREAD

**Issue by ksdrummer** [jqno/gnome-one-window-wonderland#6]
Hello,

thank you for the great extension !
Any plan for porting it to gnome 45 ?

Is the project still alive ? I hope so. Let me know if you need some testing...

**Comment by ksdrummer** [comment]
Perfect, thank you very much for this !

**Comment by jqno** [comment]
A new version supporting GNOME 45 is up. Please let me know if you run into any issues, because I have been able to fully test it myself.
