### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by ksdrummer** [jqno/gnome-one-window-wonderland#8]
Hi,

gnome 46 is out and I miss this extension !
I'm sorry I'll probably be the one reminding you the gnome updates this since I use arch. I know you can't test it but I'd be down to do it 

Thank you !

**Comment by ksdrummer** [comment]
Changing the gnome version in metadata.js did the trick and the extension seems to work fine. I let you know if I encounter any bug

**Comment by jqno** [comment]
Hi! Thanks for being the one who reminds me, and also thanks for trying to update metadata.js.
I've uploaded a new version for review, I hope it comes through soon.
