### ISSUE TITLE
Add Keyboard Shortcut to Force Window Size

### ISSUE THREAD

**Issue by rawkode** [jqno/gnome-one-window-wonderland#9]
While I know I can add an application to the force list, there are times I would like to resize a window temporarily. Files is a good example. 

The only way to restore the size with gaps is to close and open again.

I was hoping we could add a keyboard shortcut to resize the current window?

**Comment by jqno** [comment]
I've thought about adding this before, and while I don't rule out adding it in the future, it opens a can of worms that I'd prefer to avoid for now.

Fortunately, there's a good workaround, as this extension pairs really well with this one: https://extensions.gnome.org/extension/4684/useless-gaps/ I use it myself to do what you're trying to achieve. Define a hotkey in the Gnome settings for maximizing a window, and this extension will make sure it respects gaps.
